67 integrate tailwind css with react email for enhanced email design flexibility
Ionia-Devs/chameleon pull request #70
Opened 2024-01-31 23:31 UTC by JakeJeongAiden

**Description** : Add tailwind to react. Subject to change

<img width="500" alt="Screenshot 2024-01-31 at 2 47 51 PM" src="https://github.com/Ionia-Devs/chameleon/assets/146908415/54e6fccb-f081-465c-bae5-096dd45f5bb4">

Image path is set to locally. I'm not sure if emails will have the logo in this case. Doc examples were using 
```
const baseUrl = process.env.VERCEL_URL
  ? `https://${process.env.VERCEL_URL}`
  : ''
```

for path for image.

2024-01-31 23:38 UTC, DinDin985 approved these changes
lgtm! Nice work on the styling 👍

2024-02-01 00:45 UTC, Balance8 requested changes
Have you sent the test email to yourself @JakeJeongAiden ? Clean up the code here and if you need help sending it to yourself, read the resend docs or ask @BBruington n

2024-02-01 00:45 UTC, Balance8 commented on apps/chameleon/components/email-template.tsx
> +        <Container className="flex bg-stone-600 border shadow-md border-white/5 rounded-tl-[80px] rounded-br-[80px] rounded-tr-xl rounded-bl-xl my-auto mx-auto px-2 text-stone-200 text-[14px]">
lets not use tailwind arb values. Convert these to as close as possible defaults

2024-02-01 00:45 UTC, Balance8 commented on apps/chameleon/components/email-template.tsx
> +    <Tailwind
I dont think we need to bring in a config here

2024-02-01 00:45 UTC, Balance8 commented on apps/chameleon/components/email-template.tsx
> +              src={'icons/chameleon-logo-transparent-bg.png'}
you need to integrate `src={`${baseUrl}/static/icons/chameleon-logo-transparent-bg.png`}`

2024-02-01 00:45 UTC, Balance8 commented on apps/chameleon/components/email-template.tsx
> +const baseUrl = process.env.VERCEL_URL
You need to use the helper function available in https://github.com/Ionia-Devs/chameleon/blob/35fe7b10ce3a71cf4a304a3f54d91d1485ba4234/apps/chameleon/lib/utils.ts#L19-L21

2024-02-01 00:50 UTC, Balance8 commented on apps/chameleon/components/email-template.tsx
Lets go ahead and move these out of the /components folder and move them into their own folder called /email-templates/{{name-of-template.tsx}}

2024-02-01 00:51 UTC, Balance8 commented on apps/chameleon/components/email-template.tsx
>  export const EmailTemplate: React.FC<Readonly<EmailTemplateProps>> = ({
Lets give it a meaningful name to inform readers what the template does

2024-02-01 00:54 UTC, Balance8 commented
Your build is failing because you didnt install 

```
pnpm add @react-email/components -E

```

2024-02-01 02:18 UTC, BobFromIHT commented
Only note from me is I think the 'Visit Chameleon' button should be centered with the image and header, just flows better on the eyes :)
looks clean though
#

2024-02-02 02:58 UTC, Balance8 approved these changes
👍🏻

2024-02-02 03:16 UTC, merged